project:
  type: website

website:
  title: "ERC Economic development tool and resources"
  favicon: assets/images/Logo-Mark_Black.png
  navbar:
    logo-href: https://ruralinnovation.us/our-work/research_mapping/
    left:
      - href: index.qmd
        text: "ERC Economic development tool and resources"
#    right:
#      - href: about.qmd
#        text: About
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Introduction
      - section: Economic Development Tool
        contents:
          - href: tool/documentation.qmd
            text: Documentation
          - href: tool/changelog.qmd
            text: Change log
      - section: Additional resources
        contents:
          - href: themes/intro.qmd
            text: Introduction
          - themes/advocacy/index.qmd
          - themes/health/index.qmd
          - themes/environment/index.qmd
          - themes/infrastructure/index.qmd
          - themes/economy/index.qmd
          - themes/business/index.qmd


format:
  html:
    theme: 
      - minty
      - src/custom.scss
    css: assets/fonts.css
    fontcolor: "#121E22"
    linkcolor: "#00835D"
    mainfont: "Bitter"
    grid:
      sidebar-width: 350px
      body-width: 1100px
      margin-width: 250px
    toc: true

resources:
- "assets/*"

