project:
  type: website

website:
  title: "ERC Fellows: Additional resources"
  favicon: assets/images/Logo-Mark_Black.png
  navbar:
    logo-href: https://ruralinnovation.us/our-work/research_mapping/
    left:
      - href: index.qmd
        text: "ERC Fellows: Additional resources"
#    right:
#      - href: about.qmd
#        text: About
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Intro
      - section: Health
        contents:
          - href: themes/health/county-health-rankings.qmd
            text: County Health Rankings
          - href: themes/health/hrsa_map.qmd
            text: HSRA Map
      - section: Community Advocacy
        contents:
          - href: themes/access/rural-capacity-index.qmd
            text: Rural Capacity Index
      - section: Resource Access
        contents:
          - href: themes/resources/food-atlas.qmd
            text: Food Access Research Atlas
      - section: Business
        contents:
          - href: themes/business/data-axle.qmd
            text: Data Axle


format:
  html:
    theme: 
      - minty
      - src/custom.scss
    css: assets/fonts.css
    fontcolor: "#121E22"
    linkcolor: "#00835D"
    mainfont: "Bitter"
    grid:
      sidebar-width: 250px
      body-width: 1100px
      margin-width: 250px
    toc: true

resources:
- "assets/*"

