project:
  type: website

website:
  title: "Additional Resources for ERC Fellows"
  favicon: assets/images/Logo-Mark_Black.png
  navbar:
    logo-href: https://ruralinnovation.us/our-work/research_mapping/
    left:
      - href: index.qmd
        text: "ERC Fellows: Additional resources"
#    right:
#      - href: about.qmd
#        text: About
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Intro
      - section: Community Advocacy
        contents:
          - href: themes/advocacy/rural-capacity-index.qmd
            text: Rural Capacity Index
      - section: Health
        contents:
          - href: themes/health/county-health-rankings.qmd
            text: County Health Rankings
          - href: themes/health/food-atlas.qmd
            text: Food Access
          - href: themes/health/hrsa_map.qmd
            text: HSRA Map
      # - section: Resource Access
      #   contents:
      #     - href: themes/resources/food-atlas.qmd
      #       text: Food Access Research Atlas
      - section: Environment
        contents:
          - href: themes/environment/natural-amenities.qmd
            text: Natural Amenities
          - href: themes/environment/outdoor-rec.qmd
            text: Outdoor Recreation
          - href: themes/environment/air.qmd
            text: Air Quality
          - href: themes/environment/water.qmd
            text: Water Quality
      - section: Business
        contents:
          - href: themes/business/data-axle.qmd
            text: Data Axle


format:
  html:
    theme: 
      - minty
      - src/custom.scss
    css: assets/fonts.css
    fontcolor: "#121E22"
    linkcolor: "#00835D"
    mainfont: "Bitter"
    grid:
      sidebar-width: 300px
      body-width: 1100px
      margin-width: 250px
    toc: true

resources:
- "assets/*"

