---
title: "Health"
format: 
  html:
    code-fold: true
engine: knitr
reference-location: margin
---


## County Health Rankings

[Access the County Health Rankings maps and data](https://www.countyhealthrankings.org/health-data){.external target="_blank"}

County Health Rankings provide a snapshot of the overall health and well-being of communities across different counties. Published annually, these rankings assess a wide range of factors including health outcomes (such as premature death and quality of life), health behaviors (like smoking and physical activity), clinical care, social and economic conditions (such as education and employment), and the physical environment. The rankings help identify disparities between counties and highlight areas for improvement. By offering this data, they aim to inform local health initiatives, guide policy decisions, and promote efforts to enhance public health across regions.

* **Years**: Editions are available each year 2011-2024
* **Geographic level**: County
* **Territories available**: (This source only includes the 50 states and D.C.)


## Food Access Research Atlas

[Access the USDA's Food Access Research Atlas map](https://www.ers.usda.gov/data-products/food-access-research-atlas/go-to-the-atlas/){.external target="_blank"}

The USDA's Food Access Research Atlas is a comprehensive tool designed to help understand and analyze food access in the United States. It provides data on various aspects of food accessibility, including the availability of grocery stores, supermarkets, and other food retailers, as well as factors like income and transportation. By mapping these elements, the Atlas helps identify areas with limited access to healthy food options, often referred to as "food deserts." This information supports policymakers, researchers, and community organizations in developing strategies to improve food access and address nutritional disparities.

* **Year**: 2019 (Updated 2023)
* **Geographic level**: Census Tract
* **Territories available**: (This source only includes the 50 states and D.C.)


## HRSA  Map

[Access the Health Resources & Services Administration map tool](https://data.hrsa.gov/maps/map-tool/){.external target="_blank"}

The Health Resources & Services Administration (HRSA) Map Tool is an interactive platform designed to visualize and analyze health resource distribution across the United States. It provides data on healthcare facilities, such as health centers, hospitals, and specialized services, along with information on health workforce availability and health outcomes. The tool aims to support decision-making by highlighting areas with unmet health needs and guiding the allocation of resources to improve healthcare access and services in underserved communities.

* **Years**: Various data years (Updated 2024)
* **Territories available**: Several layers are available for Puerto Rico, Northern Mariana Islands, U.S. Virgin Islands, Guam, and American Samoa
