---
title: "Introduction to Additional Resources"
---


In order to assist Fellows who require data that is not supported by the Economic Development Tool, we have assembled a vetted catalog of research and data.  This catalog includes resources on the following themes...

**Community Advocacy**  
This section contains a resource to help users asses a community's leadership and ability to access funding for infrastructure projects.

**Health**  
This section contains a variety of resources to help users survey the landscape of this topic.  There are resources on health outcomes, health care access, and food desserts. 

**Environment**  
This section contains resources on the natural environment.  There is both information about natural amenities from a recreation standpoint and from a health standpoint.  

**Infrastructure**  
This section contains two interactive tools created by CORI related to broadband.  One of these tools can also help users understand potential environmental hazards in their area.  This section also contains a resource on child care access.

**Local Economy**  
This section contains a resource that provides an overview of the local economy.  Though much of this information is also available in CORI's Economic Development Tool, this resource may supplement the economic data available in CORI's tool.  

**Business**  
This section helps users access a vetted list of active businesses (with details about the business) in a given area.  This section does not provide direct access to the resource, but it does guide users through finding and accessing the resource.  
